version: '3.2'
volumes:
  postgres-data:
  bundle-cache:
services:
  app:
    build: .
    image: cthdb:alpha
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/cthdb
      - bundle-cache:/bundle
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5480:5432"
